### ISSUE TITLE
Clarify code license

### ISSUE THREAD

**Issue by JDWarner** [pebble-examples/ks-clock-face#1]
As a Pebble Time backer, I love that example code for watch faces is being made available. Thanks @C-D-Lewis!

However, before I can use this as a jumping off point, I would appreciate knowing what license (or at least what _style_ of license) it is released under. Mainly so I don't get any surprises later from e.g. the viral nature of the GPL. I'm not advocating for any particular license, just knowledge if it's permissive (BSD, MIT-like) or virally open like the GPL.

Adding a `LICENSE.txt` file at package root would be very helpful.

**Comment by matthewtole** [comment]
Hi @JDWarner,

Looks like we forgot to include the license when we uploaded the project to GitHub, so thanks for letting us know! All of our examples are released under the MIT license, and I have added just added a [LICENSE file](https://github.com/pebble-examples/ks-clock-face/blob/master/LICENSE) to the project to clarify it.
